name: Ansible CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common -y
          sudo apt-add-repository --yes --update ppa:ansible/ansible-6.4.0
          sudo apt install ansible=2.10.* -y

      - name: Configure Ansible
        run: |
          echo "[servers]" > ansible/inventory/hosts
          echo "localhost ansible_connection=local" >> ansible/inventory/hosts

      - name: Validate Ansible playbooks
        run: |
          ansible-playbook ansible/playbooks/site.yml -i ansible/inventory/hosts --syntax-check
          ansible-playbook ansible/playbooks/site.yml -i ansible/inventory/hosts --check

      - name: Deploy Ansible
        run: |
          ansible-playbook ansible/playbooks/site.yml -i ansible/inventory/hosts