name: Ansible CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ansible Galaxy dependencies
        run: ansible-galaxy install -r ansible/requirements.yml

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Ansible playbooks
        run: ansible-lint ansible/playbooks

      - name: Create artifact
        run: |
          mkdir artifacts
          cp -r ansible/ inventory/ artifacts/
        working-directory: ${{ github.workspace }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ansible-artifact
          path: artifacts/

      - name: Deploy to Dev
        run: ansible-playbook ansible/playbooks/site.yml -i ansible/inventory/hosts