- name: Create DNS records in Cloudflare
  hosts: all
  tasks:
    - name: Create DNS records
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone_id }}/dns_records"
        method: POST
        body_format: json
        headers:
          Authorization: "Bearer {{ cloudflare_api_key }}"
          Content-Type: "application/json"
        body:
          type: A
          name: "{{ dns_record.name }}"
          content: "{{ dns_record.ip }}"
          ttl: 1
      register: response

- name: Print API response
  debug:
    var: response.json