- name: Deploy Node.js backend
  hosts: nodejs_servers
  become: true

  tasks:
    - name: Install Node.js and NPM
      block:
        - name: Install prerequisites for Node.js
          ansible.builtin.apt:
            name:
              - curl
              - gnupg
            update_cache: yes

        - name: Install Node.js
          ansible.builtin.apt_key:
            url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
          ansible.builtin.apt_repository:
            repo: "deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main"
            state: present
          ansible.builtin.apt:
            name: nodejs
            update_cache: yes

    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present

    - name: Clone application repository
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        version: "{{ app_branch }}"
        force: yes

    - name: Install application dependencies
      ansible.builtin.npm:
        path: "{{ app_path }}"
        state: present

    - name: Start Node.js backend
      ansible.builtin.systemd:
        name: "{{ app_name }}.service"
        state: started
        enabled: yes

  handlers:
    - name: restart Node.js backend
      ansible.builtin.systemd:
        name: "{{ app_name }}.service"
        state: restarted