- name: Deploy my application
  hosts: all
  become: true

  vars:
    cloudflare_zone_id: "my_cloudflare_zone_id"
    cloudflare_api_key: "my_cloudflare_api_key"
    letsencrypt_email: "my_email@example.com"
    nginx_port: 80
    nginx_ssl_port: 443

  roles:
    - cloudflare
    - lets-encrypt
    - nginx
    - nodejs